name: jh_im_sdk
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #路由管理
  nav_router: 0.0.5
  #处理
  intl: 0.16.0
  #选择相册
  image_picker: 0.6.1
  #滚动文字
  marquee_flutter: ^0.1.2
  #网络图片缓存
  cached_network_image: 2.0.0
  #网络请求
  dio: ^3.0.7
  #数据池
  shared_preferences: ^0.5.4
  #提示对话框
  toast: 0.1.5
  #图片放大显示
  photo_view: 0.4.2
  #聊天框
  bubble: ^1.1.9+1
  #视频播放
  chewie: ^0.9.8+1
  #扫码
  qrscan: ^0.2.17
  #高德地图
  amap_map_fluttify: ^0.21.0
  #视频播放
  video_player: any
  #拼音
  lpinyin: ^1.0.7
  #特殊列表滑动
  azlistview: ^0.1.0
  #视酷插件
  flutter_picker: ^1.1.0
  extended_text: ^0.7.1
  extended_text_field: ^0.5.0
  extended_image: ^0.7.2
  #  multi_image_picker: ^4.6.6+rc.1
  shiku_flutter:
    path: plugin/shiku_flutter

  #时间
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/msg/
    - assets/images/tab/
    - assets/images/mine/
    - assets/images/contacts/
    - assets/images/commom/
    - assets/images/chat/
    - assets/images/emoji/
